### ISSUE TITLE
use their api instead of phones.js

### ISSUE THREAD

**Issue by zougari47** [Dun-sin/smartsearch#10]
### Description

I have seen their public API 
```js
`https://www.gsmarena.com/search-json.php3?sSearch=${input.value}`
```
so instead of running phones.js just use their API instead. This will improve server performance.
What do you think ??

**Comment by Dun-sin** [comment]
Makes no difference my friend😂

That's not an api👀
Basically that searches for a phone yes, but I will still need to do what I just did to get the data🙃

There's only one api for the gsm website and it's not free
