### ISSUE TITLE
[BUG] The detailed page looks off in Mobiles

### ISSUE THREAD

**Issue by tamalCodes** [Dun-sin/smartsearch#11]
### Description

 - The Image looks streched more than it should have been. ( Take a look at `Image 1`)
 - The texts are also too close to each other and provides an overall bad UI/UX for the mobile view

### Fixes ? 

- i would like to make the picture in a much more `contain` manner.
- Also some increased margin/padding for the texts !

## Image 1

![image](https://user-images.githubusercontent.com/72851613/187062737-31891217-9876-4087-8a6f-c477031254e8.png)

**Comment by Dun-sin** [comment]
You could just use the issue template tho😭

**Comment by Dun-sin** [comment]
If you want to work on it, go for it

**Comment by tamalCodes** [comment]
> You could just use the issue template thosob

Oops, sorry about it 😫

**Comment by thepushkaraj** [comment]
Hey @Dun-sin I would like to work on this.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin I would like to work on this.

sure

**Comment by thepushkaraj** [comment]
What changes would you like to see?

**Comment by Dun-sin** [comment]
> What changes would you like to see?

i guess you reading the issue message will be nice

**Comment by thepushkaraj** [comment]
> > What changes would you like to see?
> 
> i guess you reading the issue message will be nice

I read it already, but just confirming if you want to get changed something else that that.

**Comment by Dun-sin** [comment]
> I read it already, but just confirming if you want to get changed something else that that.

I will make a separate issue if I need to add something else

**Comment by thepushkaraj** [comment]
Great, so I'm starting to work on this.
