### ISSUE TITLE
[FEATURE] make reviews look better

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/smartsearch#23]
### Description

The review section seems complicated even tho it works, the conversation takes everything from the reply to the quote reply and add it in one box with no clear differerence between them

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by unkwnownGriot** [comment]
hi i' working on the phone page specially on the review section and  i was wondering why the element in the review array are not objects with the person who post the review , the date and the review itself  as peer key value
like this 
```js
const review = [{
user: "John",
comment: "a beautifull one"
date: new Date().toDateString() 
}]
```

**Comment by unkwnownGriot** [comment]
btw this is what i've done what do you think?


![2022-09-16 11_30_32-Window](https://user-images.githubusercontent.com/83823820/190629489-43955a7d-b130-4207-b816-b37a57cf18df.png)

**Comment by Dun-sin** [comment]
> hi i' working on the phone page specially on the review section and i was wondering why the element in the review array are not objects with the person who post the review , the date and the review itself as peer key value like this
> 
> ```js
> const review = [{
> user: "John",
> comment: "a beautifull one"
> date: new Date().toDateString() 
> }]
> ```

I did the reviews part in a rush, but I never really intended to put the names

**Comment by Dun-sin** [comment]
> btw this is what i've done what do you think?
> 
> ![2022-09-16 11_30_32-Window](https://user-images.githubusercontent.com/83823820/190629489-43955a7d-b130-4207-b816-b37a57cf18df.png)

Nice looks good

**Comment by unkwnownGriot** [comment]
> > hi i' working on the phone page specially on the review section and i was wondering why the element in the review array are not objects with the person who post the review , the date and the review itself as peer key value like this
> > ```js
> > const review = [{
> > user: "John",
> > comment: "a beautifull one"
> > date: new Date().toDateString() 
> > }]
> > ```
> 
> I did the reviews part in a rush, but I never really intended to put the names

ok i see but it was just a suggestion
