### ISSUE TITLE
[DOCS] add readme file

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/smartsearch#7]
### Description

`Readme.md` file is needed to describe the project and give instructions and how to contribute, including the technologies used

use [this](https://github.com/Dun-sin/anon-chat-app) as a guide

**Comment by SRADHA-SURESH12** [comment]
Hey, can I work on this issue?

**Comment by Dun-sin** [comment]
> Hey, can I work on this issue?

Sure, go ahead
