### ISSUE TITLE
[DOCS] add contributing file

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/smartsearch#8]
### Description

Contributing.md file should cover details on how to contribute to this project

use [this](https://github.com/Dun-sin/trick-generator/blob/main/CONTRIBUTING.md) as a demo

**Comment by hasnainmakada-99** [comment]
Hey @Dun-sin I would like to work on this issue, Will you please assign it to me ?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin I would like to work on this issue, Will you please assign it to me ?

Sure

**Comment by hasnainmakada-99** [comment]
Sorry @Dun-sin you assigned this issue to yourself only, I told you to assign it to me

**Comment by Dun-sin** [comment]
> Sorry @Dun-sin you assigned this issue to yourself only, I told you to assign it to me

Sorry, mistake.

**Comment by hasnainmakada-99** [comment]
> > Sorry @Dun-sin you assigned this issue to yourself only, I told you to assign it to me
> 
> Sorry, mistake.

It's ok

**Comment by Dun-sin** [comment]
@hasnainmakada-99 I needed to add the rules because people are starting to contribute to this and going against some rules. I will change the tasks for this

**Comment by hasnainmakada-99** [comment]
Can you please be more specific about what you said @Dun-sin

**Comment by hasnainmakada-99** [comment]
> Can you please be more specific about what you said @Dun-sin 

Because i didn't understand what you said that's why 😃

**Comment by Dun-sin** [comment]
> > Can you please be more specific about what you said @Dun-sin
> 
> Because i didn't understand what you said that's why 😃

I created the contributing.md file and added the rules that was in the description of this issue because people are starting to contribute to this project and breaking the rules I wanted in contributing.md file.

So now I updated this issue, meaning read the issue again because the task as changed a little

**Comment by hasnainmakada-99** [comment]
> > > Can you please be more specific about what you said @Dun-sin
> > 
> > 
> > Because i didn't understand what you said that's why 😃
> 
> I created the contributing.md file and added the rules that was in the description of this issue because people are starting to contribute to this project and breaking the rules I wanted in contributing.md file.
> 
> So now I updated this issue, meaning read the issue again because the task as changed a little

Ok now I got it @Dun-sin , So now what are new tasks & changes which you'll like to make me with the contributing.md file

**Comment by hasnainmakada-99** [comment]
Ok @Dun-sin, I am going to use the demo file as a reference while making the contributing.md file, And I'll also keep the rules in mind which you've added in the contributing md of your project

**Comment by Dun-sin** [comment]
> Ok @Dun-sin, I am going to use the demo file as a reference while making the contributing.md file, And I'll also keep the rules in mind which you've added in the contributing md of your project

awesome, thank you

**Comment by hasnainmakada-99** [comment]
> > Ok @Dun-sin, I am going to use the demo file as a reference while making the contributing.md file, And I'll also keep the rules in mind which you've added in the contributing md of your project
> 
> awesome, thank you

You're welcome

**Comment by hasnainmakada-99** [comment]
@Dun-sin now that this issue is solved, Close it so others won't comment on it

**Comment by Dun-sin** [comment]
> @Dun-sin now that this issue is solved, Close it so others won't comment on it

This was something else you could do in the pull request if you read the comments well, there was a way to automatically close this too

**Comment by hasnainmakada-99** [comment]
> > @Dun-sin now that this issue is solved, Close it so others won't comment on it
> 
> This was something else you could do in the pull request if you read the comments well, there was a way to automatically close this too

Ohh so sorry, I didn't knew that, I'm just beginner right now that's why

**Comment by Dun-sin** [comment]
Using this, automatically closes this issue

![IMG_20220829_033855](https://user-images.githubusercontent.com/78784850/187112217-c95ba142-636a-4242-949c-dc39169ed65b.jpg)

**Comment by hasnainmakada-99** [comment]
> Using this, automatically closes this issue
> 
> ![IMG_20220829_033855](https://user-images.githubusercontent.com/78784850/187112217-c95ba142-636a-4242-949c-dc39169ed65b.jpg)

Now I got it, Thank you for telling me, I've learned so much new from you

**Comment by Dun-sin** [comment]
> > Using this, automatically closes this issue
> > ![IMG_20220829_033855](https://user-images.githubusercontent.com/78784850/187112217-c95ba142-636a-4242-949c-dc39169ed65b.jpg)
> 
> Now I got it, Thank you for telling me, I've learned so much new from you

Glad to help❤️
And thanks for contributing
